[target.x86_64-unknown-linux-gnu] # 或你的目標平台
linker = "clang" # mold 建議搭配 clang 使用
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

# 如果你的 clang/gcc 版本夠新，可以直接指定 linker
# [target.x86_64-unknown-linux-gnu]
# linker = "mold"
